---
name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "tar gz"
        run: |
          tar -czf my-file.txt.tar.gz my-file.txt
      - name: "tar bz"
        run: |
          tar -cjf my-file.txt.tar.bz my-file.txt
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Development Build"
          files: |
            my-file.txt
            my-file.txt.tar.bz
            my-file.txt.tar.gz
